### ISSUE TITLE
SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1018)

### ISSUE THREAD

**Issue by PatrikTrestik** [PatrikTrestik/homeassistant_nicegate#2]
> Hi Patrick,
> 
> i came across your integration in search of something less complicated than the Homekit installation for the IT4WIFI.
> Unfortunately, i can't pass the second site of the config flow (where the "setup code" is to be entered). 
> The config flow stays at that site with "Unknown error occurred". I entered the code from the device in the form xxx-xx-xxx.
> 
> Looking closer to the HA logs:
> 
> "SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1018)"
> ```
> Traceback (most recent call last):
>   File "/config/custom_components/nicegate/nice_api.py", line 224, in pair
>     reader, writer = await asyncio.open_connection(self.host, 443, ssl=ctx)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> And another error (but may point to the identical problem):)
> 
> "Error handling request"
> ```
> File "/config/custom_components/nicegate/config_flow.py", line 67, in async_step_pair
>     user_input=await self.pair_device(self.data)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nicegate/config_flow.py", line 119, in pair_device
>     raise InvalidAuth
> custom_components.nicegate.config_flow.InvalidAuth
> ```
> 
> Not having dug deeper yet, but is ist possible that (SSL) security updates in HA have outdated the method your integration interacts with the IT4WIFI bridge?
> 
> Thank you,
> Leo 

 _Originally posted by @apollon9 in [#1](https://github.com/PatrikTrestik/homeassistant_nicegate/issues/1#issuecomment-2637691549)_

**Comment by PatrikTrestik** [comment]
It seams as SSL problem and can be connected with updates done in recent HA version.
I'll look on it.

On the other hand, it works in my house without problem. Might be it is only initial setup issue.

I'll have time not earlier than next week, please be patient. 😄

**Comment by PatrikTrestik** [comment]
Please confirm that it is fixed.

I unfortunately could not test initial setup on my hardware.

Reopen this issue if there is still error. Thanks.

**Comment by apollon9** [comment]
Initial setup still cannot be completed,
The fix leads to a different error message:
`[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1018)`

reopen requested.

**Comment by PatrikTrestik** [comment]
@apollon9 I tested SSL handshake and all works in my environment without problem.

It could be caused by either or both:
- Your Nice BT4WiFi is really old and contains obsolete SSL. But I don't think this is a case.
- You are running on OS with really strict default options for OpenSSL.

On which OS are you running HA?

Can you plase run this  "openssl s_client -connect gate.lan:443 -state" and send me result.

**Comment by apollon9** [comment]
My HA runs on raspberry pi:

 OS Version:               Home Assistant OS 14.2
  Home Assistant Core:      2025.2.2

 ```
~ uname -a      
Linux a0d7b954-ssh 6.6.62-haos-raspi #1 SMP PREEMPT Mon Jan 27 11:21:12 UTC 2025 aarch64 Linux

 ~ openssl s_client -connect 192.168.1.151:443 -state
CONNECTED(00000003)
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS write client hello
SSL3 alert write:fatal:handshake failure
SSL_connect:error in error
4080C300567F0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../ssl/statem/extensions.c:893:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 79 bytes and written 300 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: C180A129F8E186A394DFDFE92D6DB90AA51737BD239A5A80EB9C415125483FFF
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1739298228
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

```

**Comment by PatrikTrestik** [comment]
Hmm. Your device is sending no certificate at all. It is really odd.

Did you configured it for other integration before? Could it be in Apple Home mode?

Definitely it is problem on device side. We have to figure out how to reset it.

Can you please send me type of the device?

**Comment by apollon9** [comment]
This is really strange.
I have a Nice IT4WIFI bought 3years ago. _edit_: it runs fw ver. 0.3.14 which seems the only or most recent version.
It was very difficult to connect the device with the home network via app.
As a result of trying your HA integration, the gate was thrown out of the app again.
I made a full factory reset of the IT4WIFI - since that, i am not able to connect it to home net any more. _edit_: successfully regained access with different mobile phone.
Which interface do you use? I currently consider buying the BIDI-Wifi device hoping that it is easier to connect..

**Comment by PatrikTrestik** [comment]
I have IT4WIFI too and it works for me almost 2 years. But I remember that geting it to local Wifi network and initial setup was pain.
I used MyNice Pro app on mobile. Once it was setup for WiFi and connected HA Integration wporks with it.

Unfortunately it is hard to guess what is wrong without phisical presence. 

Are you able to connect with MyNice Pro?

**Comment by apollon9** [comment]
Today i tried MyNice Pro, but i could not make any successful connection.
From the manual i read that in the Pro app you could also update the firmware - which FW version is yours?

**Comment by PatrikTrestik** [comment]
1) I was incorrect. My hardware is BiDi-WiFi. Small dongle inside gate motor. But I think that it is nearly same.
2) You have to start with complete reset. It is cca chapter 8 in manual. You have to get device to Wifi AP state. You will see "NiceIT4WIFlxxxxxx" wifi network.
3) Use android or iOS without new/clever wifi settings. All "automatic" selection and other stuff creshes the process. I used old tablet because I was not able to do it on my new phone.
4) You have to be near and exactly on same WiFi network. Not only in same LAN, but physicaly connected to same WiFi. I had problems because I have two WiFi access points and setup process will not cross between them.

I wish you a luck with setup.

**Comment by apollon9** [comment]
1. I assume it is not exactly the same, see ssl error. 
4. Wifi could be an issue - i use several AP, though in the same network / ip range, with different MAC.

This device also works from outside wifi range (over cellular/LTE), going through AWS server (captured traffic with wireshark - goes to 'eu-central-1.compute.amazonaws.com').
This is probably the reason why it doesn't work with your integration (and also a good reason not to use it at all).
The port used seems to be 31346/tcp. Data is TLSv1.2 encrypted

my solution: Ordered a BiDi-Wifi device in italy.

**Comment by mattf06** [comment]
Hi @PatrikTrestik, 
I just bought my IT4WIFI this week and installed it and I have the same problem: [nicegate] [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1018)
Firmware was updated during installation.
It works well with the iOS MyNice app.

HAAS version:
OS Version:                    Home Assistant OS 14.2
Home Assistant Core:    2025.2.5

Thanks for your support.

Update: I'm doing some tests (on Windows) and I'm able to do pairing in Python 3.8. Python 3.12 failed! I think the issue comes from openssl delivered with the python version.
Update 2: adding ctx.set_ciphers('DEFAULT:@SECLEVEL=0') solve the issue, but only with python 3.12 on Windows. Doesn't work inside HAAS :(

**Comment by PatrikTrestik** [comment]
>  It works well with the iOS MyNice app.

So you configured it for HomeKit? If yes it will con communicate with this integration at all.
Integration is for MyNice mode. You should configure it initialy with "MyNice Pro" app.
See https://www.youtube.com/watch?v=cOJ-qmeME88

**Comment by mattf06** [comment]
Configured for HomeKit... I don't think so. I need to use the MyNice app (not the MyNice Pro or MyNice Welcome or MyNice Welcome NH) to control my gate. My aim is to control my gate via HAAS, I don't care to the MyNice app.
About my personnal testing, I'm able to do the pairing with python 3.13.2 on Windows 10 with a small test program outside HAAS.
pair() returns the password/token, but when I try connect() I got ssl error : SSL handshake is taking longer than 60.0 seconds: aborting the connection

**Comment by PatrikTrestik** [comment]
>About my personnal testing, I'm able to do the pairing with python 3.13.2 on Windows 10 with a small test program outside HAAS. pair() returns the password/token, but when I try connect() I got ssl error : SSL handshake is taking longer than 60.0 seconds: aborting the connection

Great. We are at least on right road 😄 
Are you using my nice_api.py or some your variant?

After pair() you have to go to MyNice app and asign user correct permission. User starts with no permission and that is why it will not connect. 
After pair note the password and use it to initialize NiceGateApi next time.

Unfortunately I could not test on my device now. If you are in mood of coding, we can some time connect on wapp.
+420 seven-seven-4854-(10-4)-63

**Comment by memtew** [comment]
Hi, I have the same error:

````
2026-01-29 23:22:23.045 ERROR (MainThread) [nicegate] SSL handshake is taking longer than 60.0 seconds: aborting the connection
Traceback (most recent call last):
  File "/config/custom_components/nicegate/nice_api.py", line 226, in pair
    reader, writer = await asyncio.open_connection(self.host, 443, ssl=ctx)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lambda: protocol, host, port, **kwds)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1201, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        ssl_shutdown_timeout=ssl_shutdown_timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1234, in _create_connection_transport
    await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection
````

Openssl answer on my server:
````
CONNECTED(00000003)
depth=0 C = IT, ST = Treviso, L = Oderzo, O = Nice Spa, OU = RD, CN = IT4WIFI
verify error:num=18:self signed certificate
verify return:1
depth=0 C = IT, ST = Treviso, L = Oderzo, O = Nice Spa, OU = RD, CN = IT4WIFI
verify return:1
write W BLOCK
---
Certificate chain
 0 s:/C=IT/ST=Treviso/L=Oderzo/O=Nice Spa/OU=RD/CN=IT4WIFI
   i:/C=IT/ST=Treviso/L=Oderzo/O=Nice Spa/OU=RD/CN=IT4WIFI
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDlzCCAn+gAwIBAgIJALubjDH7Dpt1MA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNV
BAYTAklUMRAwDgYDVQQIDAdUcmV2aXNvMQ8wDQYDVQQHDAZPZGVyem8xETAPBgNV
BAoMCE5pY2UgU3BhMQswCQYDVQQLDAJSRDEQMA4GA1UEAwwHSVQ0V0lGSTAeFw0x
NjExMjQwOTM5MDhaFw0zNjExMTkwOTM5MDhaMGIxCzAJBgNVBAYTAklUMRAwDgYD
VQQIDAdUcmV2aXNvMQ8wDQYDVQQHDAZPZGVyem8xETAPBgNVBAoMCE5pY2UgU3Bh
MQswCQYDVQQLDAJSRDEQMA4GA1UEAwwHSVQ0V0lGSTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAN34gcg/I1tkqGW3GFNFb9V9yirojDseb+LDRFD0j9Zq
th2VmxM+Kcx515u10YZeYpP44UChfgKD9KCCA7pkq/1UqLqMnSSs+bEWjc+aHBCr
Bx8Uc3rSsQId+Ut1rdztxdg5o9TiJRHKkTiQ/gzFERQZNRp83KahY1CQmsRM/3qk
jNV2ekVVTGI/21R1E01KAzKS7hJxDp6m+IqitYrEAMAOIhg557v5MDXJRHY04AyN
KcteCY4BYfnLX9NYZfOfrulgzdzUu8BkOd/tKa8J1RcOAtAmzvJAFwK1HK/Abwt+
iW08cfj+5CBamDJsP8Wd5xR9vWESqbRYpKGu8uOsE0UCAwEAAaNQME4wHQYDVR0O
BBYEFNEDzhfYVR3H4sRN4kLVQpw63D69MB8GA1UdIwQYMBaAFNEDzhfYVR3H4sRN
4kLVQpw63D69MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAKITorO2
gTygyYe3RqUfdo8GZp3g/KyUM46FatO0PzfCO5ddBSgW4sHnH3J796LtPlaZotFS
nKpjYIXY+FJTOzb0gH6yTmHMm2RqKblIz94A8J/gkHqDGLX4yNF9bsUurwyS6P9f
GZAgymzMxefyJBn8UKVgq+10sgWHIf63VumP5Aijxj7awPMkNy2U+NBwILX6MtM9
lrfJ7ZYyU/LskIq3qVtSCE1lNjxPLsYobzbLK1L6+fIHXkP01BWgGEM8W5N1F6y0
OUzkkDKx6emAmIhXz39FzMOa3C5+XkbYIYxtNa7YjVeo6o1LjcsL+DSLahVAn+xN
5k/GtRXSpNcn0rU=
-----END CERTIFICATE-----
subject=/C=IT/ST=Treviso/L=Oderzo/O=Nice Spa/OU=RD/CN=IT4WIFI
issuer=/C=IT/ST=Treviso/L=Oderzo/O=Nice Spa/OU=RD/CN=IT4WIFI
---
No client certificate CA names sent
Server Temp Key: DH, 1024 bits
---
SSL handshake has read 1776 bytes and written 517 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES256-SHA256
    Session-ID: A999619EAE8AF23D25801021BA7F827B043B4CCA71B3D1C90C6AF0FCA2F26798
    Session-ID-ctx: 
    Master-Key: 9671613B64B09D7F4229A521E7B066D2D4C5E6D4161EA9480AA01C60EC4C97B8CCEE44D9ABC624FD3A4834A70BF20848
    Start Time: 1769708999
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
---
````

Python script on my server nice.py connecting to gates successfully. On HAOS server openssl can't get cert from gates:
````
CONNECTED (00000003)
SSL_connect:before SSL initialization
SSL_connect: SSL03/TLS write client hello
SSL connect:SSL03/TLS write client hello
SSL3 alert write: fatal:handshake failure
SSL connect:error in error
40C755A1907F0000: error: 00000152:SSL routines: final_renegotiate:unsafe legacy renegotiation disabled:
ssl/staten/extensions.c:947:
----
no peer certificate available
----
No client certificate CA names sent
SSL handshake has read 79 bytes and written 316 bytes
Verification: OK
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
Protocol: TLSv1.2
Cipher : 0000
Session-ID:
4399CE8DBB4C7843450084D323B3ZFCBA6AE141F4984E5082E4F07388192E186
Session-ID-ctx:
Master-Key:
PSK identity: None
PSK identity hint: None
SRP username: None
Start Time: 1769719443
Tineout : 7200 (sec)
Verify return code: 0 (ok)
Extended master secret: no
````

**Comment by memtew** [comment]
OK, this code did the trick:
```
            ctx.verify_mode = ssl.CERT_NONE
            ctx.set_ciphers("DEFAULT:@SECLEVEL=0")
            ctx.minimum_version = ssl.TLSVersion.TLSv1_2
            ctx.maximum_version = ssl.TLSVersion.TLSv1_2
```
Now IT4WIFI successfully added and connected to HA. But need to check, that this code didnt broke new adapter (BIDI-WIFI) connection.
